AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudCrew Academy Cognito User Pool and Identity Pool'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Environment name

Resources:
  # Cognito User Pool
  CloudCrewUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'cloudcrew-users-${Environment}'
      AliasAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      EmailVerificationSubject: 'Welcome to CloudCrew Academy - Verify Your Email'
      EmailVerificationMessage: 'Welcome to CloudCrew Academy! Your verification code is {####}. Start your cloud engineering journey today!'
      VerificationMessageTemplate:
        EmailMessage: 'Welcome to CloudCrew Academy! Your verification code is {####}. Ready to launch your tech career?'
        EmailSubject: 'CloudCrew Academy - Email Verification'
        DefaultEmailOption: CONFIRM_WITH_CODE
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          TemporaryPasswordValidityDays: 7
      Schema:
        - Name: email
          Required: true
          Mutable: true
          AttributeDataType: String
        - Name: given_name
          Required: true
          Mutable: true
          AttributeDataType: String
        - Name: family_name
          Required: true
          Mutable: true
          AttributeDataType: String
        - Name: phone_number
          Required: false
          Mutable: true
          AttributeDataType: String
        - Name: subscription_tier
          Mutable: true
          AttributeDataType: String
          DeveloperOnlyAttribute: false
        - Name: city
          Mutable: true
          AttributeDataType: String
          DeveloperOnlyAttribute: false
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
        InviteMessageAction: EMAIL
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: false
        DeviceOnlyRememberedOnUserPrompt: true

  # User Pool Client for Web App
  CloudCrewUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'cloudcrew-web-client-${Environment}'
      UserPoolId: !Ref CloudCrewUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:3001/auth/callback
        - https://cloudcrew.academy/auth/callback
      LogoutURLs:
        - http://localhost:3001/
        - https://cloudcrew.academy/
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      PreventUserExistenceErrors: ENABLED
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 24
      IdTokenValidity: 24
      RefreshTokenValidity: 30

  # User Pool Domain
  CloudCrewUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub 'cloudcrew-academy-${Environment}-${AWS::AccountId}'
      UserPoolId: !Ref CloudCrewUserPool

  # Identity Pool for accessing AWS services
  CloudCrewIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub 'CloudCrew_Academy_${Environment}'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CloudCrewUserPoolClient
          ProviderName: !GetAtt CloudCrewUserPool.ProviderName

  # Authenticated Role for Identity Pool
  CognitoAuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CloudCrew_CognitoAuthRole_${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CloudCrewIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: CognitoAuthorizedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                  - cognito-identity:*
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - 'arn:aws:s3:::cloudcrew-user-content/*'

  # Unauthenticated Role for Identity Pool
  CognitoUnauthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CloudCrew_CognitoUnauthRole_${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CloudCrewIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': unauthenticated
      Policies:
        - PolicyName: CognitoUnauthorizedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - mobileanalytics:PutEvents
                  - cognito-sync:*
                Resource: '*'

  # Attach roles to Identity Pool
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CloudCrewIdentityPool
      Roles:
        authenticated: !GetAtt CognitoAuthenticatedRole.Arn
        unauthenticated: !GetAtt CognitoUnauthenticatedRole.Arn

Outputs:
  UserPoolId:
    Description: 'Cognito User Pool ID'
    Value: !Ref CloudCrewUserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: 'Cognito User Pool Client ID'
    Value: !Ref CloudCrewUserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  UserPoolArn:
    Description: 'Cognito User Pool ARN'
    Value: !GetAtt CloudCrewUserPool.Arn
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolArn'

  IdentityPoolId:
    Description: 'Cognito Identity Pool ID'
    Value: !Ref CloudCrewIdentityPool
    Export:
      Name: !Sub '${AWS::StackName}-IdentityPoolId'

  UserPoolDomain:
    Description: 'Cognito User Pool Domain'
    Value: !Sub 'https://${CloudCrewUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolDomain'

  AuthenticatedRoleArn:
    Description: 'Authenticated Role ARN'
    Value: !GetAtt CognitoAuthenticatedRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AuthenticatedRoleArn'