# CloudCrew Academy - Production Deployment Configuration

service: cloudcrew-academy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'dev'}
  environment:
    STAGE: ${self:provider.stage}
    DYNAMODB_TABLE_PREFIX: ${self:service}-${self:provider.stage}
    COGNITO_USER_POOL_ID: ${self:custom.cognitoUserPoolId}
    COGNITO_CLIENT_ID: ${self:custom.cognitoClientId}
    STRIPE_SECRET_KEY: ${ssm:/cloudcrew/${self:provider.stage}/stripe/secret-key}
    S3_BUCKET_NAME: ${self:custom.s3BucketName}
    CLOUDFRONT_DOMAIN: ${self:custom.cloudfrontDomain}
  
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:service}-${self:provider.stage}-*"
        
        - Effect: Allow
          Action:
            - s3:GetObject
            - s3:PutObject
            - s3:DeleteObject
          Resource:
            - "arn:aws:s3:::${self:custom.s3BucketName}/*"
        
        - Effect: Allow
          Action:
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminDeleteUser
            - cognito-idp:AdminGetUser
            - cognito-idp:AdminUpdateUserAttributes
          Resource:
            - "arn:aws:cognito-idp:${self:provider.region}:*:userpool/${self:custom.cognitoUserPoolId}"

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-domain-manager

custom:
  # Environment-specific configurations
  cognitoUserPoolId:
    dev: us-east-1_DevPoolId
    staging: us-east-1_StagingPoolId
    prod: us-east-1_ProdPoolId
  
  cognitoClientId:
    dev: dev-client-id
    staging: staging-client-id
    prod: prod-client-id
  
  s3BucketName:
    dev: cloudcrew-dev-content
    staging: cloudcrew-staging-content
    prod: cloudcrew-prod-content
  
  cloudfrontDomain:
    dev: dev-cdn.cloudcrew.academy
    staging: staging-cdn.cloudcrew.academy
    prod: cdn.cloudcrew.academy
  
  # Domain management
  customDomain:
    domainName:
      dev: dev-api.cloudcrew.academy
      staging: staging-api.cloudcrew.academy
      prod: api.cloudcrew.academy
    certificateName: '*.cloudcrew.academy'
    createRoute53Record: true
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
  
  # Build configuration
  esbuild:
    bundle: true
    minify: true
    target: node18
    exclude:
      - aws-sdk
    watch:
      pattern: ['src/**/*.ts']
      ignore: ['node_modules/**', '.serverless/**']

functions:
  # Authentication functions
  auth-register:
    handler: src/handlers/auth.register
    events:
      - http:
          path: auth/register
          method: post
          cors: true
    timeout: 30
  
  auth-login:
    handler: src/handlers/auth.login
    events:
      - http:
          path: auth/login
          method: post
          cors: true
    timeout: 30
  
  auth-confirm:
    handler: src/handlers/auth.confirmSignUp
    events:
      - http:
          path: auth/confirm
          method: post
          cors: true
    timeout: 30
  
  # User management
  users-profile:
    handler: src/handlers/users.getProfile
    events:
      - http:
          path: users/profile
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.cognitoAuthorizer}
    timeout: 30
  
  users-update:
    handler: src/handlers/users.updateProfile
    events:
      - http:
          path: users/profile
          method: put
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.cognitoAuthorizer}
    timeout: 30
  
  # Course management
  courses-list:
    handler: src/handlers/courses.getCourses
    events:
      - http:
          path: courses
          method: get
          cors: true
    timeout: 30
  
  courses-detail:
    handler: src/handlers/courses.getCourseDetail
    events:
      - http:
          path: courses/{courseId}
          method: get
          cors: true
    timeout: 30
  
  courses-enroll:
    handler: src/handlers/courses.enrollCourse
    events:
      - http:
          path: courses/{courseId}/enroll
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.cognitoAuthorizer}
    timeout: 30
  
  # Progress tracking
  progress-get:
    handler: src/handlers/progress.getProgress
    events:
      - http:
          path: courses/{courseId}/progress
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.cognitoAuthorizer}
    timeout: 30
  
  progress-update:
    handler: src/handlers/progress.updateProgress
    events:
      - http:
          path: courses/{courseId}/progress
          method: put
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.cognitoAuthorizer}
    timeout: 30
  
  # Payment processing
  payments-create:
    handler: src/handlers/payments.createPaymentIntent
    events:
      - http:
          path: payments/create-intent
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.cognitoAuthorizer}
    timeout: 30
  
  payments-confirm:
    handler: src/handlers/payments.confirmPayment
    events:
      - http:
          path: payments/confirm
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${self:custom.cognitoAuthorizer}
    timeout: 30

resources:
  Resources:
    # DynamoDB Tables
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-users
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
    
    CoursesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-courses
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: courseId
            AttributeType: S
          - AttributeName: category
            AttributeType: S
        KeySchema:
          - AttributeName: courseId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CategoryIndex
            KeySchema:
              - AttributeName: category
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
    
    UserProgressTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-user-progress
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: courseId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: courseId
            KeyType: RANGE
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
    
    PaymentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-payments
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: paymentId
            AttributeType: S
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: paymentId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: UserIndex
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
    
    # S3 Bucket for content storage
    ContentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName.${self:provider.stage}}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        VersioningConfiguration:
          Status: Enabled
        LifecycleConfiguration:
          Rules:
            - Status: Enabled
              Transitions:
                - TransitionInDays: 30
                  StorageClass: STANDARD_IA
                - TransitionInDays: 90
                  StorageClass: GLACIER
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: ['*']
              AllowedMethods: [GET, PUT, POST, DELETE, HEAD]
              AllowedOrigins: ['*']
              MaxAge: 3000
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
    
    # CloudFront Distribution
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Aliases:
            - ${self:custom.cloudfrontDomain.${self:provider.stage}}
          Origins:
            - Id: S3Origin
              DomainName: ${self:custom.s3BucketName.${self:provider.stage}}.s3.amazonaws.com
              S3OriginConfig:
                OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
            Compress: true
          CacheBehaviors:
            - PathPattern: '/videos/*'
              TargetOriginId: S3Origin
              ViewerProtocolPolicy: redirect-to-https
              CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed-CachingDisabled
              Compress: true
          Enabled: true
          PriceClass: PriceClass_100
          ViewerCertificate:
            AcmCertificateArn: !Ref SSLCertificate
            SslSupportMethod: sni-only
            MinimumProtocolVersion: TLSv1.2_2021
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
    
    # CloudFront Origin Access Identity
    CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment: !Sub 'OAI for ${self:service}-${self:provider.stage}'
    
    # SSL Certificate
    SSLCertificate:
      Type: AWS::CertificateManager::Certificate
      Properties:
        DomainName: ${self:custom.cloudfrontDomain.${self:provider.stage}}
        ValidationMethod: DNS
        DomainValidationOptions:
          - DomainName: ${self:custom.cloudfrontDomain.${self:provider.stage}}
            HostedZoneId: ${self:custom.hostedZoneId}
        Tags:
          - Key: Environment
            Value: ${self:provider.stage}
          - Key: Service
            Value: ${self:service}
    
    # Cognito User Pool (if not using existing)
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-${self:provider.stage}-users
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: true
            Required: true
          - Name: name
            AttributeDataType: String
            Mutable: true
            Required: true
        Tags:
          Environment: ${self:provider.stage}
          Service: ${self:service}
    
    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        UserPoolId: !Ref CognitoUserPool
        ClientName: ${self:service}-${self:provider.stage}-client
        GenerateSecret: false
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
          - USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        TokenValidityUnits:
          AccessToken: hours
          IdToken: hours
          RefreshToken: days
        AccessTokenValidity: 1
        IdTokenValidity: 1
        RefreshTokenValidity: 30

  Outputs:
    ApiGatewayRestApiId:
      Value: !Ref ApiGatewayRestApi
      Export:
        Name: ${self:service}-${self:provider.stage}-api-id
    
    ApiGatewayRestApiRootResourceId:
      Value: !GetAtt ApiGatewayRestApi.RootResourceId
      Export:
        Name: ${self:service}-${self:provider.stage}-api-root-id
    
    CloudFrontDistributionId:
      Value: !Ref CloudFrontDistribution
      Export:
        Name: ${self:service}-${self:provider.stage}-cloudfront-id
    
    CloudFrontDomainName:
      Value: !GetAtt CloudFrontDistribution.DomainName
      Export:
        Name: ${self:service}-${self:provider.stage}-cloudfront-domain
    
    ContentBucketName:
      Value: !Ref ContentBucket
      Export:
        Name: ${self:service}-${self:provider.stage}-content-bucket
    
    CognitoUserPoolId:
      Value: !Ref CognitoUserPool
      Export:
        Name: ${self:service}-${self:provider.stage}-cognito-pool-id
    
    CognitoUserPoolClientId:
      Value: !Ref CognitoUserPoolClient
      Export:
        Name: ${self:service}-${self:provider.stage}-cognito-client-id