service: cloudcrew-video-infrastructure

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    # S3 Bucket for Video Storage
    VideoStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: cloudcrew-videos-${self:provider.stage}
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedMethods:
                - GET
                - HEAD
                - PUT
                - POST
              AllowedHeaders:
                - '*'
              MaxAge: 3000
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
        LifecycleConfiguration:
          Rules:
            - Id: DeleteIncompleteMultipartUpload
              Status: Enabled
              AbortIncompleteMultipartUpload:
                DaysAfterInitiation: 7
        VersioningConfiguration:
          Status: Enabled

    # S3 Bucket Policy for CloudFront Access
    VideoStorageBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref VideoStorageBucket
        PolicyDocument:
          Statement:
            - Sid: AllowCloudFrontAccess
              Effect: Allow
              Principal:
                Service: cloudfront.amazonaws.com
              Action: s3:GetObject
              Resource: !Sub '${VideoStorageBucket.Arn}/*'
              Condition:
                StringEquals:
                  AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${VideoCloudFrontDistribution}'

    # CloudFront Origin Access Control
    VideoOriginAccessControl:
      Type: AWS::CloudFront::OriginAccessControl
      Properties:
        OriginAccessControlConfig:
          Name: cloudcrew-videos-oac-${self:provider.stage}
          OriginAccessControlOriginType: s3
          SigningBehavior: always
          SigningProtocol: sigv4

    # CloudFront Distribution for Video Delivery
    VideoCloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: true
          Comment: CloudCrew Academy Video Distribution
          DefaultRootObject: index.html
          Origins:
            - Id: S3-cloudcrew-videos
              DomainName: !GetAtt VideoStorageBucket.RegionalDomainName
              OriginAccessControlId: !GetAtt VideoOriginAccessControl.Id
              S3OriginConfig: {}
          DefaultCacheBehavior:
            TargetOriginId: S3-cloudcrew-videos
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            MinTTL: 0
            DefaultTTL: 86400
            MaxTTL: 31536000
          CacheBehaviors:
            - PathPattern: '*.m3u8'
              TargetOriginId: S3-cloudcrew-videos
              ViewerProtocolPolicy: redirect-to-https
              AllowedMethods:
                - GET
                - HEAD
              Compress: true
              ForwardedValues:
                QueryString: true
                Cookies:
                  Forward: none
              MinTTL: 0
              DefaultTTL: 5
              MaxTTL: 10
            - PathPattern: '*.ts'
              TargetOriginId: S3-cloudcrew-videos
              ViewerProtocolPolicy: redirect-to-https
              AllowedMethods:
                - GET
                - HEAD
              Compress: false
              ForwardedValues:
                QueryString: false
                Cookies:
                  Forward: none
              MinTTL: 0
              DefaultTTL: 86400
              MaxTTL: 31536000
          PriceClass: PriceClass_100
          ViewerCertificate:
            CloudFrontDefaultCertificate: true

    # DynamoDB Table for Video Metadata
    VideoMetadataTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cloudcrew-video-metadata-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: videoId
            AttributeType: S
          - AttributeName: courseId
            AttributeType: S
        KeySchema:
          - AttributeName: videoId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: CourseIdIndex
            KeySchema:
              - AttributeName: courseId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    # DynamoDB Table for Video Progress Tracking
    VideoProgressTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: cloudcrew-video-progress-${self:provider.stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: videoId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: videoId
            KeyType: RANGE
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

  Outputs:
    VideoStorageBucketName:
      Description: S3 Bucket for Video Storage
      Value: !Ref VideoStorageBucket
      Export:
        Name: ${self:provider.stage}-VideoStorageBucket

    VideoCloudFrontDomain:
      Description: CloudFront Distribution Domain
      Value: !GetAtt VideoCloudFrontDistribution.DomainName
      Export:
        Name: ${self:provider.stage}-VideoCloudFrontDomain

    VideoMetadataTableName:
      Description: DynamoDB Table for Video Metadata
      Value: !Ref VideoMetadataTable
      Export:
        Name: ${self:provider.stage}-VideoMetadataTable

    VideoProgressTableName:
      Description: DynamoDB Table for Video Progress
      Value: !Ref VideoProgressTable
      Export:
        Name: ${self:provider.stage}-VideoProgressTable
